# Default Values
# Defines number of rows to be generated in the CSV File
number_of_rows: 3
file_name: "MRMC"
action: "random"
available_field: [account_holder_name,address,ifsc_code,micr_code,branch_name,account_type,account_number,opening_balance,closing_balance,debit,credit,date,total_balance]
target_field: [ifsc_code]
available_label: ['Account Name', 'Account Number', 'Account Type', 'Address', 'Branch Name', 'Closing Balance', 'Credit', 'Debit', 'IFSC Code', 'MICR Code', 'Opening Balance', 'Date', 'Total Balance']
target_label: ['Account Name', 'Account Number', 'Account Type', 'Address', 'Branch Name', 'Closing Balance', 'Credit', 'Debit', 'IFSC Code', 'MICR Code', 'Opening Balance', 'Date', 'Total Balance']
default: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    account_number: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
account_holder_name:
      # Account holder names in small letters
    small_names: 1  
      # Account holder names in capital letters
    capital_names: 1 
      # Account holder names in only 3 letters
    short_names: 1 
      # Account holder names have 25 letters?
    long_names: 1 
      # Account holder names not have gaps
    no_gap_names: 1 
      # Account holder names have dots between the names
    dot_names: 1  
      # Account holder names not have a title
    no_title_names: 1 
address:
      # Can Contain "single" or "double" or "three" or "four", Only valid on Default Locale
      # Default and only value for India is "single"
    address_line: "single" 
      # True or False
    wrong_state: false 
      # Length of the Pin Code , default: , else use other lengths 3 upto 5
    pincode_length: 5
      # Should have Pincode? True / False
    has_pincode: false
      # Gap between address True / False
    no_gap_address: true
account_number:
      # Use Default Normal Faker Generation , if False other settings combination will be used
    normal: [false,1]
      # Size of the Account Number , can be less than 7 or more than 20
    account_number_length: [7,1]
      # Should it have alphabets? true / false, besides number it can also have alphabets if true , default value false
    has_alphabet: [false,1]
      # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
     # Account Number is a Blank field , if true makes the output blank or emppty string, default false
    blank: [false, 1]
ifsc_code:
    # Use Default Normal Indian Bank Scheme Based Generation , if False other settings combination will be used
    normal: [false,1]
    # Ifsc code is less than 11 characters 
    ifsc_code_length: [11,1]
    # number other than 0 in the fifth field.
    has_alphabet: [true,1]
    # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
    # ifsc_code is a Blank field , if true makes the output blank or empty string, default false
    blank: [false, 1]
    # Wrong Format
    faulty: [true,1]
opening_balance:
      # The range between which the number would lie
    start_range: 1000
    end_range: 2000
    has_alphabet: [true,1]
    # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
    # Blank field , if true makes the output blank or empty string, default false
    blank: [false, 1]

closing_balance:
      # The range between which the number would lie
    start_range: 1000
    end_range: 2000
    has_alphabet: [true,1]
    # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
    # Blank field , if true makes the output blank or empty string, default false
    blank: [false, 1]

debit:
      # The range between which the number would lie
    start_range: 1000
    end_range: 2000
    has_alphabet: [true,1]
    # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
    # Blank field , if true makes the output blank or empty string, default false
    blank: [false, 1]

credit:
      # The range between which the number would lie
    start_range: 1000
    end_range: 2000
    has_alphabet: [true,1]
    # Should it have special character ? true / false , default value false
    has_special_characters: [false,1]
    # Blank field , if true makes the output blank or empty string, default false
    blank: [false, 1]

