# Default Values
askari-bank: 
    account_holder_name: "MUKHTAR AHMAD BASHIR AHMAD"
    address: |
      Chak No.55/DB Yazman
      District Bahawalpur
      Pakistan
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: "Current"
    opening_balance: "10,895.92"
    closing_balance: "32,978.69"
    debit: "1,779.95"
    credit: "23,862.72"
    date: ""
    total_balance: "32,978.69"
axis-bank: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
hdfc-bank(1): 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
icici-bank(1): 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
icici-bank(2): 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
MeinL-Bank: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
MRMC: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
PNB-Bank-ok: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
Regions-Bank-Statement: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
sbh-bank: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
sbi-bank: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
sbi-ok: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""
TD-Bank: 
    account_holder_name: ""
    address: ""
    ifsc_code: ""
    micr_code: ""
    branch_name: ""
    account_type: ""
    opening_balance: ""
    closing_balance: ""
    debit: ""
    credit: ""
    date: ""
    total_balance: ""