# Default Values
# Defines number of rows to be generated in the CSV File
number_of_rows: 1
file_name: askari-bank
available_field: [account_holder_name, address, ifsc_code, micr_code, branch_name,
  account_type, opening_balance, closing_balance, debit, credit, date, total_balance]
target_field: [account_holder_name, address, account_type]
default:
  account_holder_name: MUKHTAR AHMAD BASHIR AHMAD
  address: "Chak No.55/DB Yazman\nDistrict Bahawalpur\nPakistan\n"
  ifsc_code: ''
  micr_code: ''
  branch_name: ''
  account_type: Current
  opening_balance: 10,895.92
  closing_balance: 32,978.69
  debit: 1,779.95
  credit: 23,862.72
  date: ''
  total_balance: 32,978.69
account_holder_name:
      # Account holder names in small letters
  small_names: 1
  capital_names: 1
  short_names: 1
  long_names: 1
  no_gap_names: 1
  dot_names: 1
  no_title_names: 1
address:
      # Can Contain "single" or "double" or "three" or "four"
  address_line: single
  wrong_state: false
