# Default Values
# Defines number of rows to be generated in the CSV File
number_of_rows: 3
file_name: axis-bank
available_field: [account_holder_name, address, ifsc_code, micr_code, branch_name,
  account_type, account_number, opening_balance, closing_balance, debit, credit, date,
  total_balance]
target_field: [account_holder_name, address, account_type, account_number]
default:
  account_holder_name: THANIGAIVEL BHEEMARAJ S
  address: "NO 11 NEELAMEGAM STREET KAMARAJ NAGAR AVADI\nCHENNAI\nTAMIL NADU-INDIA\
    \ 600071\n"
  ifsc_code: ''
  micr_code: ''
  branch_name: ''
  account_type: SALARY
  opening_balance: '345.08'
  closing_balance: '200.00'
  debit: '420366.35'
  credit: '420221.27'
  date: ''
  total_balance: ''
  account_number: ''
account_holder_name:
      # Account holder names in small letters
  small_names: 1
  capital_names: 1
  short_names: 1
  long_names: 1
  no_gap_names: 1
  dot_names: 1
  no_title_names: 1
address:
      # Can Contain "single" or "double" or "three" or "four"
  address_line: single
  wrong_state: false
