# Default Values
# Defines number of rows to be generated in the CSV File
number_of_rows: 1
file_name: sbh-bank
available_field: [account_holder_name, address, ifsc_code, micr_code, branch_name,
  account_type, account_number, opening_balance, closing_balance, debit, credit, date,
  total_balance]
target_field: [account_holder_name, address, account_type, account_number]
default:
  account_holder_name: Mr. DUDIGAM ANJANAILU
  address: ''
  ifsc_code: SBHY0020076
  micr_code: '500004054'
  branch_name: SANATHNAGAR HYDERABAD
  account_type: ''
  account_number: '00000052208489170'
  opening_balance: 12,599.85
  closing_balance: 4,751.85
  debit: ''
  credit: ''
  date: ''
  total_balance: ''
account_holder_name:
      # Account holder names in small letters
  small_names: 1
  capital_names: 3
  short_names: 1
  long_names: 1
  no_gap_names: 1
  dot_names: 1
  no_title_names: 2
address:
      # Can Contain "single" or "double" or "three" or "four", Only valid on Default Locale
      # Default and only value for India is "single"
  address_line: single
  wrong_state: false
  pincode_length: 5
  has_pincode: true
  no_gap_address: false
